module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: true,
  },
  plugins: ['@typescript-eslint'],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/strict-type-checked',
    'plugin:@typescript-eslint/stylistic-type-checked',
  ],
  env: {
    browser: true,
    es2024: true,
  },
  rules: {
    '@typescript-eslint/consistent-type-definitions': [2, 'type'],
    '@typescript-eslint/no-floating-promises': 0,
    'block-scoped-var': 2,
    camelcase: 2,
    'capitalized-comments': 2,
    curly: 2,
    'default-case-last': 2,
    'default-param-last': 0,
    'dot-notation': 0,
    eqeqeq: 2,
    'func-style': 2,
    'grouped-accessor-pairs': 2,
    'id-length': [2, { min: 1, max: 20 }],
    indent: [2, 2],
    'line-comment-position': 2,
    'max-depth': 2,
    'max-lines': 2,
    'max-lines-per-function': 2,
    'max-params': [2, { max: 5 }],
    'new-cap': 2,
    'no-await-in-loop': 2,
    'no-constant-binary-expression': 2,
    'no-constructor-return': 2,
    'no-duplicate-imports': 2,
    'no-else-return': 2,
    'no-empty-function': 2,
    'no-eval': 2,
    'no-label-var': 2,
    'no-lone-blocks': 2,
    'no-lonely-if': 2,
    'no-multi-str': 2,
    'no-new-native-nonconstructor': 2,
    'no-proto': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-shadow': 2,
    'no-template-curly-in-string': 2,
    'no-underscore-dangle': 2,
    'no-unneeded-ternary': 2,
    'no-unreachable-loop': 2,
    'no-unused-private-class-members': 2,
    'no-use-before-define': 2,
    'no-useless-concat': 2,
    'no-var': 2,
    'no-void': 2,
    'prefer-spread': 2,
    'prefer-template': 2,
    quotes: [2, 'single'],
    semi: [2, 'never'],
  },
}
